version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven and Java
      - yum install -y java-1.8.0-openjdk-devel
      - yum install -y maven

  pre_build:
    commands:
      - echo Preparing the build environment
      - mvn clean

  build:
    commands:
      - echo Building the Java application
      - mvn compile
      - echo Running unit tests
      - mvn test

  post_build:
    commands:
      - echo Packaging the Java application
      - mvn package
      - echo Build and package complete

    # Uploading the JAR file to the S3 bucket
      - echo Uploading build artifacts to S3
      - aws s3 cp target/*.jar s3://satish219/builds/ --recursive

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
  base-directory: target








